### ISSUE TITLE
Travis fails expecting keyboard input when compiling

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [P2PSP/p2psp-console#17]
A timeout of 5 seconds (Travis waits for 10) should be implemented.

**Comment by agauniyal** [comment]
@vicente-gonzalez-ruiz depending on what you want - `yes | ./make.py` should work here - https://github.com/P2PSP/console/blob/master/.travis.yml#L19

**Comment by agauniyal** [comment]
You can close this issue 😸  - https://github.com/P2PSP/console/pull/18

**Comment by vicente-gonzalez-ruiz** [comment]
Thanks!
